from textblob import TextBlob
from textblob.sentiments import NaiveBayesAnalyzer
import os

'''
Given a directory of text files generated by newspaper performs sentiment analysis with text glob.

The polarity score is a float within the range [-1.0, 1.0]. 
The subjectivity is a float within the range [0.0, 1.0] where 0.0 is very objective and 1.0 is very subjective.

'''
#http://textblob.readthedocs.org/en/dev/quickstart.html#sentiment-analysis
#http://textblob.readthedocs.org/en/dev/advanced_usage.html#sentiment-analyzers


os.chdir("/Users/jgiesler/Desktop/PythonTwitter/data/forsentimate")
datafile = open("sentiment.txt",'wt')
files = os.listdir()
files = [s for s in files if ".txt" in s] #get all text files
count = 0
for i in files:
	num_lines = sum(1 for line in open(i,'rt'))
	if(num_lines > 0): # if the file has data we can do the next steps
		file_in = open(i,'rt')
		filestr = ""
		title = file_in.readline()
		filename = file_in.readline()
		url = file_in.readline()
		for line in file_in:
			line = line.rstrip()
			filestr += line
		if(len(filestr) > 1000): # if its a substantial
			#metadata (title, filenumber, url)
			print(title.rstrip(),file = datafile)
			print("Filename :"+filename.rstrip(), file = datafile)
			print(url.rstrip(),file = datafile)
			
			#data (Polarity/subjectivty, positive/negative)
			objectiveness = TextBlob(filestr)
			print(objectiveness.sentiment,file = datafile)

			#this didn't end up working. but there you can use this instead to perform NLP
			#happy_sad = TextBlob(filestr,analyzer=NaiveBayesAnalyzer())
			#print(happy_sad.sentiment,file = datafile)
			print("",file = datafile)
		file_in.close()
	count += 1 
	print(str(count)+ "\r", end ='')
print("\a")
datafile.close()



